[alias]
esp32c3 = "build --no-default-features --features=esp32c3 --target=riscv32imc-unknown-none-elf"
esp32s3 = "build --no-default-features --features=esp32s3,ble,ap --target=xtensa-esp32s3-none-elf"

# default target for esp32s3
target = "xtensa-esp32s3-none-elf"

[target.'cfg(target_arch = "riscv32")']
rustflags = [
  "-C", "force-frame-pointers",
]

[target.'cfg(target_arch = "xtensa")']
rustflags = [
  "-C", "link-arg=-nostartfiles",
]


[unstable]
build-std = ["alloc", "core"]
